version: "3.7"

services:
    certbot-certonly:
        image: certbot/certbot:latest
        volumes:
            - certbot:/etc/letsencrypt
        ports:
            - 80:80
        command: "
            certonly --standalone \
                     --email ${CERTBOT_CERT_EMAIL} \
                     --agree-tos \
                     --non-interactive \
                     -d ${APP_URL} \
                     -d ${PHPMYADMIN_URL}
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.253

    certbot-renew:
        image: certbot/certbot:latest
        container_name: certbot
        hostname: certbot
        volumes:
            - certbot:/etc/letsencrypt
        command: "
            renew --quiet \
                  --no-self-upgrade \
                  --dry-run
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.254

networks:
    mynet:
        name: mynet
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/24"

volumes: 
    certbot:
        name: certbot