version: "3.7"

services:
    certbot:
        image: certbot/certbot:latest
        container_name: certbot
        hostname: certbot
        volumes:
            - ./certbot/certs:/etc/letsencrypt
            - ./certbot/webroot:/var/www/certbot_webroot
        command: >
            "certonly --webroot \
                      --email ${CERTBOT_EMAIL} \
                      --agree-tos \
                      --non-interactive \
                      --cert-name ${CERTBOT_CERT_NAME}
                      -w /var/www/certbot_webroot \
                      -d ${APP_URL}
                      -d ${PHPMYADMIN_URL}
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.254

networks:
    mynet:
        name: mynet
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/24"