version: "3.7"

services:
    certbot-certificates:
        image: certbot/certbot:latest
        container_name: certbot
        hostname: certbot
        volumes:
            - certbot:/etc/letsencrypt
            - webroot:/var/www/certbot_webroot
        command: "
            certificates
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.252

    certbot-certonly:
        image: certbot/certbot:latest
        volumes:
            - certbot:/etc/letsencrypt
            - webroot:/var/www/certbot_webroot
        command: "
            certonly --webroot \
                     --agree-tos \
                     --non-interactive \
                     --email ${CERTBOT_CERT_EMAIL} \
                     --cert-name ${CERTBOT_CERT_NAME} \
                     -w /var/www/certbot_webroot \
                     -d ${APP_URL} \
                     -d ${PHPMYADMIN_URL}
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.253

    certbot-renew:
        image: certbot/certbot:latest
        container_name: certbot
        hostname: certbot
        volumes:
            - certbot:/etc/letsencrypt
            - webroot:/var/www/certbot_webroot
        command: "
            renew --quiet \
                  --no-self-upgrade
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.254

networks:
    mynet:
        name: mynet
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/24"

volumes: 
    certbot:
        name: certbot
    webroot:
        name: webroot