version: "3.7"

services:
    nginx-proxy:
        image: nginx:1.17.8
        container_name: nginx-proxy
        hostname: nginx-proxy
        volumes:
            - ./conf/nginx/mysite.conf:/etc/nginx/mysite.conf
            - ./certbot/certs:/etc/nginx/certs
            - ./certbot/webroot:/var/www/certbot_webroot
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            - APP_URL=${APP_URL}
            - PHPMYADMIN_URL=${PHPMYADMIN_URL}
            - CERTBOT_WEBROOT=${CERTBOT_WEBROOT}
        command: >
            /bin/bash -c "
                envsubst < /etc/nginx/mysite.conf > /etc/nginx/nginx.conf \
                && exec nginx -g 'daemon off;'
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.2

    app:
        image: php:7.4.3-fpm
        container_name: app
        hostname: app
        working_dir: /var/www/html
        command: >
            /bin/bash -c "
                echo \"<?php phpinfo();\" > test.php | php -S 0.0.0.0:80
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.5

    mysql:
        image: mysql:5.7.29
        container_name: mysql
        hostname: mysql
        volumes: 
            - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            mynet: 
                ipv4_address: 172.28.0.3

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        hostname: phpmyadmin
        external_links:
            - mysql:db
        networks:
            mynet: 
                ipv4_address: 172.28.0.4

networks:
    mynet:
        name: mynet
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/24"