version: "3.7"

services:
    nginx-proxy:
        image: nginx:1.17.8-perl
        container_name: nginx-proxy
        hostname: nginx-proxy
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - certbot:/etc/letsencrypt
            - webroot:/var/www/certbot_webroot
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            - APP_URL=${APP_URL}
            - PHPMYADMIN_URL=${PHPMYADMIN_URL}
            - CERTBOT_CERT_NAME=${CERTBOT_CERT_NAME}
        networks:
            mynet:
                ipv4_address: 172.28.0.2

    app:
        image: php:7.4.3
        container_name: app
        hostname: app
        working_dir: /var/www/html
        environment: 
            - MYSQL_HOST=172.28.0.3
            - MYSQL_USER=root
            - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes: 
            - ./app:/var/www/html
        expose: 
            - 80
        command: >
            /bin/bash -c "
                docker-php-ext-install pdo pdo_mysql && php -S 0.0.0.0:80
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.5

    mysql:
        image: mysql:5.7.29
        container_name: mysql
        hostname: mysql
        volumes: 
            - ./conf/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            mynet: 
                ipv4_address: 172.28.0.3

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        hostname: phpmyadmin
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
        networks:
            mynet: 
                ipv4_address: 172.28.0.4

networks:
    mynet:
        name: mynet
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/24"

volumes:
    certbot:
        name: certbot
    webroot:
        name: webroot
    mysql:
        name: mysql
