version: "3.7"

services:
    nginx-proxy:
        image: nginx:1.17.8
        container_name: nginx-proxy
        hostname: nginx-proxy
        volumes:
            - ./conf.d/nginx:/etc/nginx/conf.d
            - certbot:/etc/letsencrypt
            - webroot:/var/www/certbot_webroot
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            - APP_URL=${APP_URL}
            - PHPMYADMIN_URL=${PHPMYADMIN_URL}
            - CERTBOT_CERT_NAME=${CERTBOT_CERT_NAME}
        command: >
            /bin/bash -c "
                envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf \
                && exec nginx -g 'daemon off;'
            "
        networks:
            mynet:
                ipv4_address: 172.28.0.2

    app:
        image: node:13.12.0
        container_name: app
        hostname: app
        working_dir: /var/www/html
        environment: 
            - MYSQL_HOST=mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes: 
            - ./app:/var/www/html
        expose: 
            - 80
        command: "npm start"
        networks:
            mynet:
                ipv4_address: 172.28.0.5

    mysql:
        image: mysql:5.7.29
        container_name: mysql
        hostname: mysql
        volumes: 
            - ./conf.d/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            mynet: 
                ipv4_address: 172.28.0.3

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        hostname: phpmyadmin
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
        networks:
            mynet:
                ipv4_address: 172.28.0.4

networks:
    mynet:
        name: mynet
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/24"

volumes:
    certbot:
        name: certbot
    webroot:
        name: webroot
    mysql:
        name: mysql
